# Generated by Django 4.2 on 2026-06-17 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecin', '0006_testlaboratoire'),
        ('reception', '0005_alter_patient_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('specialite', models.CharField(choices=[('Cardiologue', 'Cardiologue'), ('Biologiste', 'Biologiste'), ('Général', 'Général')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plainte_patient', models.TextField()),
                ('resultat', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('encours', 'En cours'), ('termine', 'Terminé')], default='attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_laboratoire', to='reception.patient')),
                ('rendezvous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_laboratoire', to='medecin.rendezvous')),
                ('specialiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_laboratoire', to='medecin.specialiste')),
                ('test_demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_laboratoire', to='laboratoire.testlaboratoire')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plainte_patient', models.TextField()),
                ('examen_demande', models.TextField()),
                ('envoyer_labo', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('rendezvous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_laboratoire', to='medecin.rendezvous')),
                ('specialiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_laboratoire', to='medecin.specialiste')),
            ],
        ),
    ]
