# Generated by Django 4.2 on 2026-06-17 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_alter_patient_statut'),
        ('medecin', '0007_prescription'),
        ('laboratoire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandelaboratoire',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.patient'),
        ),
        migrations.AlterField(
            model_name='demandelaboratoire',
            name='rendezvous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.rendezvous'),
        ),
        migrations.AlterField(
            model_name='demandelaboratoire',
            name='specialiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.specialiste'),
        ),
        migrations.AlterField(
            model_name='demandelaboratoire',
            name='test_demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoire.testlaboratoire'),
        ),
        migrations.DeleteModel(
            name='AnalyseLaboratoire',
        ),
    ]
