# Generated by Django 4.2 on 2026-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0002_alter_demandelaboratoire_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlaboratoire',
            name='specialite',
            field=models.CharField(max_length=100),
        ),
    ]
