# Generated by Django 4.2 on 2026-06-19 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0004_laborantin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.TextField()),
                ('statut', models.CharField(choices=[('valide', 'Validé'), ('rejete', 'Rejeté'), ('en_cours', 'En cours')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laboratoire.demandelaboratoire')),
            ],
        ),
    ]
