# Generated by Django 4.2 on 2026-06-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0005_resultatlaboratoire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandelaboratoire',
            name='resultat',
        ),
        migrations.AlterField(
            model_name='demandelaboratoire',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('encours', 'En cours'), ('termine', 'Terminé'), ('pret_medecin', 'Prêt médecin')], default='attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='resultatlaboratoire',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('encours', 'En cours'), ('termine', 'Terminé')], default='termine', max_length=20),
        ),
    ]
