# Generated by Django 4.2 on 2026-06-24 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0006_remove_demandelaboratoire_resultat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultatlaboratoire',
            name='resultat',
        ),
        migrations.AddField(
            model_name='resultatlaboratoire',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultatlaboratoire',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat_labo', to='laboratoire.demandelaboratoire'),
        ),
        migrations.CreateModel(
            name='ValeurResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='laboratoire.testlaboratoire')),
            ],
        ),
        migrations.AddField(
            model_name='resultatlaboratoire',
            name='valeurs',
            field=models.ManyToManyField(blank=True, to='laboratoire.valeurresultat'),
        ),
    ]
