# Generated by Django 4.2 on 2026-06-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0009_alter_prescription_rendezvous_and_more'),
        ('laboratoire', '0007_remove_resultatlaboratoire_resultat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandelaboratoire',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='demandelaboratoire',
            name='specialiste',
        ),
        migrations.RemoveField(
            model_name='resultatlaboratoire',
            name='valeurs',
        ),
        migrations.AddField(
            model_name='resultatlaboratoire',
            name='valeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratoire.valeurresultat'),
        ),
        migrations.AlterField(
            model_name='demandelaboratoire',
            name='rendezvous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_labo', to='medecin.rendezvous'),
        ),
        migrations.AlterField(
            model_name='resultatlaboratoire',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='laboratoire.demandelaboratoire'),
        ),
        migrations.AlterField(
            model_name='resultatlaboratoire',
            name='statut',
            field=models.CharField(choices=[('normal', 'Normal'), ('anormal', 'Anormal'), ('critique', 'Critique')], default='normal', max_length=20),
        ),
    ]
