# Generated by Django 4.2 on 2026-06-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0008_remove_demandelaboratoire_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultatlaboratoire',
            name='valeur',
        ),
        migrations.AddField(
            model_name='resultatlaboratoire',
            name='valeurs',
            field=models.ManyToManyField(blank=True, to='laboratoire.valeurresultat'),
        ),
        migrations.AlterField(
            model_name='resultatlaboratoire',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat_labo', to='laboratoire.demandelaboratoire'),
        ),
        migrations.AlterField(
            model_name='resultatlaboratoire',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('encours', 'En cours'), ('termine', 'Terminé')], default='termine', max_length=20),
        ),
    ]
