# Generated by Django 4.2 on 2026-06-12 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_alter_patient_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='statut',
            field=models.CharField(choices=[('reception', 'Reception'), ('en_cours', 'En cours'), ('attente_medecin', 'Attente médecin'), ('en_consultation', 'En consultation'), ('termine', 'Terminé')], default='reception', max_length=20),
        ),
    ]
