# Generated by Django 4.2 on 2026-06-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_patient_created_at_alter_patient_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='statut',
            field=models.CharField(choices=[('reception', 'Reception'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='reception', max_length=20),
        ),
    ]
