# Generated by Django 4.2 on 2026-06-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_alter_patient_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='statut',
            field=models.CharField(choices=[('reception', 'Réception'), ('envoye', 'Envoyé au spécialiste'), ('en_cours', 'En cours de traitement'), ('termine', 'Terminé'), ('labo', 'Envoyé au laboratoire')], default='reception', max_length=30),
        ),
    ]
