# Generated by Django 4.2 on 2026-07-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0010_disponibilitespecialiste'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=15000, max_digits=10)),
                ('provider', models.CharField(choices=[('orange_money', 'Orange Money'), ('m_pesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('wave', 'Wave')], default='orange_money', max_length=30)),
                ('numero_tel', models.CharField(max_length=20)),
                ('reference', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='patient.profilpatient')),
                ('rendezvous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='medecin.rendezvous')),
            ],
        ),
    ]
