# Generated by Django 4.2 on 2026-06-11 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_alter_patient_statut'),
        ('medecin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(max_length=100)),
                ('observation_medecin', models.TextField()),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='En attente', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.patient')),
            ],
        ),
        migrations.AddField(
            model_name='specialiste',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.patient'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='specialiste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecin.specialiste'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
