# Generated by Django 4.2 on 2026-06-12 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_alter_patient_statut'),
        ('medecin', '0002_examen_specialiste_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='specialiste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens', to='medecin.specialiste'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='observation_medecin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='reception.patient'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='reception.patient'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='specialiste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous', to='medecin.specialiste'),
        ),
    ]
