# Generated by Django 4.2 on 2026-06-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0003_examen_specialiste_alter_examen_observation_medecin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='examen',
            name='type_examen',
            field=models.CharField(choices=[('electrophorese_hemoglobine', "Électrophorèse de l'hémoglobine"), ('groupage_sanguin', 'Groupage sanguin'), ('vih', 'Test VIH'), ('hepatite', 'Hépatite B/C')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialiste',
            name='specialite',
            field=models.CharField(choices=[('electrophorese', 'Électrophorèse'), ('hematologie', 'Hématologie'), ('biologie', 'Biologie Médicale'), ('general', 'Médecine Générale')], default='general', max_length=50),
        ),
    ]
