# Generated by Django 4.2 on 2026-06-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0004_alter_examen_statut_alter_examen_type_examen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plainte_patient', models.TextField()),
                ('examen_demande', models.TextField()),
                ('envoyer_labo', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='specialiste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecin.specialiste'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé')], default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialiste',
            name='specialite',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Examen',
        ),
        migrations.AddField(
            model_name='analyselaboratoire',
            name='rendezvous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.rendezvous'),
        ),
        migrations.AddField(
            model_name='analyselaboratoire',
            name='specialiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.specialiste'),
        ),
    ]
