# Generated by Django 4.2 on 2026-06-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0005_analyselaboratoire_alter_rendezvous_specialiste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
            ],
        ),
    ]
