# Generated by Django 4.2 on 2026-06-17 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0006_testlaboratoire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField()),
                ('traitement', models.TextField()),
                ('conseils', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('rendezvous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.rendezvous')),
                ('specialiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.specialiste')),
            ],
        ),
    ]
