# Generated by Django 4.2 on 2026-06-17 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medecin', '0007_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyselaboratoire',
            name='rendezvous',
        ),
        migrations.RemoveField(
            model_name='analyselaboratoire',
            name='specialiste',
        ),
        migrations.DeleteModel(
            name='TestLaboratoire',
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialiste',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialiste', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AnalyseLaboratoire',
        ),
    ]
