# Generated by Django 4.2 on 2026-06-19 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medecin', '0008_remove_analyselaboratoire_rendezvous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='rendezvous',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='medecin.rendezvous'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='specialiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medecin.specialiste'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='specialiste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous', to='medecin.specialiste'),
        ),
        migrations.AlterField(
            model_name='specialiste',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialiste_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
