# Generated by Django 4.2 on 2026-07-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0009_alter_prescription_rendezvous_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibiliteSpecialiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('specialiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='medecin.specialiste')),
            ],
        ),
    ]
